### PR TITLE
Register framework into seneca options. Fixes #40

### LINKED ISSUE #40: Register framework into seneca options to be used by other plugins

### PR DESCRIPTION
**Pull request by mirceaalexandru**

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Is this now reading from the same value Chairo is setting?

**Comment by mirceaalexandru** [comment]
@mcdonnelldean I will take a look on the tests

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Super that's the goal here, that you don't have to set it, it reads the value set by Chairo

**Comment by geek** [comment]
@mirceaalexandru this can't be merged at the moment

**Comment by mirceaalexandru** [comment]
@geek, yes, I will fix this tomorrow morning.

**Pull request merged**
