### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
The same usual :)

### CODE REVIEW

**Comment by geek** [comment]
@AdrieanKhisbe thoughts on the failing test?

**Comment by AdrieanKhisbe** [comment]
No Idea.
It was already failing when I was on master. (ad I retrieve, and it refails on my machine).

Didn't have time to dig. Was doing it at a meetup three quarter listening to the talks.

**Comment by AdrieanKhisbe** [comment]
(I don't know why, I suspect seneca 0.9.3)

**Comment by AdrieanKhisbe** [comment]
and I was right. Tests passes after a `npm i seneca@0.9.2``

(thought there is still some seneca error that appears:)

```
2015-12-21T22:01:29.017Z d6rxkvlc22js/1450735289009/5608/- INFO	hello	Seneca/0.9.2/d6rxkvlc22js/1450735289009/5608/-


  ....2015-12-21T22:01:29.289Z jjhtcipur32n/1450735289287/5608/- INFO	hello	Seneca/0.9.2/jjhtcipur32n/1450735289287/5608/-
PASS STARTWARE FAIL TEST
.2015-12-21T22:01:29.334Z iu9ysu08ww0i/1450735289333/5608/- INFO	hello	Seneca/0.9.2/iu9ysu08ww0i/1450735289333/5608/-
......2015-12-21T22:01:29.394Z iu9ysu08ww0i/1450735289333/5608/- ERROR	act	p0       	OUT		cmd:e0,role:api	3	{cmd:e0,role:api,d1:e1,d2:e2,did:(o9jao),fixedargs:{},context:{}}	ENTRY	(yc5hu)	-	seneca: Action cmd:e0,role:api failed: e0.	act_execute	{id:w3yuuo9qhtu4/r56jbwka4z10,gate:false,ungate:false,desc:cmd:e0,role:api,plugin:{name:p0,tag:-},time:{start:1	Error: e0
    at Seneca.<anonymous> (/Users/abecchis/git-adot/-seneca-forks/seneca-web/test/configure-server.js:56:14)
    at Object.execspec.fn (/Users/abecchis/git-adot/-seneca-forks/seneca-web/node_modules/seneca/seneca.js:1201:24)
    at Immediate._onImmediate (/Users/abecchis/git-adot/-seneca-forks/seneca-web/node_modules/seneca/node_modules/gate-executor/gate-executor.js:108:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
.2015-12-21T22:01:29.398Z iu9ysu08ww0i/1450735289333/5608/- ERROR	act	p0       	OUT		cmd:e1,role:api	0	{cmd:e1,role:api,d1:e1,d2:e2,did:(eaibf),fixedargs:{},context:{}}	ENTRY	(8yo3z)	-	seneca: Action cmd:e1,role:api failed: e1.	act_execute	{id:af6dez7avy3w/1bz10noetmek,gate:false,ungate:false,desc:cmd:e1,role:api,plugin:{name:p0,tag:-},time:{start:1	Error: e1
    at Seneca.<anonymous> (/Users/abecchis/git-adot/-seneca-forks/seneca-web/test/configure-server.js:60:14)
    at Object.execspec.fn (/Users/abecchis/git-adot/-seneca-forks/seneca-web/node_modules/seneca/seneca.js:1201:24)
    at Immediate._onImmediate (/Users/abecchis/git-adot/-seneca-forks/seneca-web/node_modules/seneca/node_modules/gate-executor/gate-executor.js:108:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
.............

25 tests complete
Test duration: 732 ms
No global variable leaks detected
```

**Comment by AdrieanKhisbe** [comment]
Here is the failing test:

```js
  test('bad', function(done) {
    var cc = 0
    var lsi = seneca( {log:'silent',debug:{undead:true} , errhandler:function(err){
      assert.equal('seneca: Action role:web failed: web-use: The property \'pin\' is missing and is always required\
 (parent: spec)..',err.message)
      cc++ && done()
    }})
    lsi.use('../web.js')
    lsi.use( function bad(){
      this.act({role:'web',use:{}})
    })
  })
```

(just giving you the leads I have before to go Zzzzzzz :sleeping:

**Comment by ckiss** [comment]
@geek @AdrieanKhisbe this test was waiting for errhandler to be called the second time to call `done()` and since this was fixed in seneca0.9.3 the use of cc is not required anymore. I'll fix this in my already opened PR.

**Comment by AdrieanKhisbe** [comment]
thanks @ckiss ! :)

**Pull request merged**
