### PR TITLE
Support of attachments. 

### PR DESCRIPTION
**Pull request by giulioroggero**
If the response message has the formart {'attachment':<base64 data>} the response is decoded and sent with res.download express method.

```
cb(null, { attachment: data.toString('base64') });
```

is managed as power point mime and not as JSON

### CODE REVIEW

**Comment by giulioroggero** [comment]
Hi there,
can you please help me on this build? Which is the threshold to pass all tests? How can I test this new feature. It's not clear to me where to add the test of attachments. Thanks!

**Comment by giulioroggero** [comment]
Hi, news about this pull request?

**Comment by mcdonnelldean** [comment]
Hey @giulioroggero Someone may be able to look at it this week. It would be nice to have a test proving it works however.

**Comment by mcdonnelldean** [comment]
@giulioroggero I'm going to close as in V.next how to support this changes.

In the end it's easier to just provide the ability to personally respond in cases where you need things like attachments. I've added an example below to illustrate how you can access the reply directly in v.next.

https://github.com/senecajs/seneca-web/blob/9721ccc00b1d42cd04d354cb50e8cf92272826c0/docs/examples/example.js

**Pull request closed without merging**
